name: RSI Alert & Chart Update
on:
  schedule:
    - cron: "*/15 * * * *"  # 15분마다 실행
  workflow_dispatch:

jobs:
  rsi-monitoring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pandas numpy plotly

    - name: Run RSI Script
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: python rsi_script.py

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rsi_chart.html
        git commit -m "Auto-update RSI chart"
        git push
